name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: prepare .env
        run: |
          cp .env.example .env
      - name: npm install, build, test and lint
        run: |
          npm ci
          npm run build --if-present
          npm run test-full
          npm run lint-full
        env:
          CI: true
